"use client";

import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ChartDetail } from "@/components/ui/chart-detail";
import type { ChartUnit } from "@/lib/chart-core";
import { formatChartValue } from "@/lib/chart-core";
import type { NutritionReportDay } from "@/lib/nutrition/reports-core";
import { chartDomain, chartTickIndexes, chartX, chartY, lineSegments } from "@/lib/nutrition/report-chart-core";

const WIDTH = 320; const HEIGHT = 152; const LEFT = 48; const RIGHT = 12;
type LineSeries = { label: string; values: Array<number | null>; className: string; dash?: string; width?: number };

function dateLabel(value: string, year = false) { return new Intl.DateTimeFormat("es-AR", { day: "numeric", month: "short", ...(year ? { year: "numeric" } : {}), timeZone: "UTC" }).format(new Date(`${value}T12:00:00Z`)).replace(" de ", " ").replace(".", ""); }
function points(values: ReturnType<typeof lineSegments>[number]) { return values.map((point) => `${point.x},${point.y}`).join(" "); }
function keySelect(event: React.KeyboardEvent<SVGElement>, select: () => void) { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); select(); } }

function ChartLegend({ series }: { series: LineSeries[] }) { return <ul className="flex flex-wrap gap-x-3 gap-y-1 text-xs text-muted-foreground" aria-label="Leyenda">{series.map((item) => <li key={item.label} className="flex items-center gap-1.5"><svg className={`h-2.5 w-5 ${item.className}`} viewBox="0 0 20 10" aria-hidden><path d="M1 5h18" fill="none" stroke="currentColor" strokeWidth={item.width ?? 2} strokeDasharray={item.dash} /></svg>{item.label}{item.dash ? " (línea discontinua)" : ""}</li>)}</ul>; }

function DateLabels({ dates }: { dates: string[] }) { const indexes = chartTickIndexes(dates.length); return <div className="relative mt-1 h-4 text-[10px] text-muted-foreground" aria-hidden>{indexes.map((index) => <span key={dates[index]} className="absolute -translate-x-1/2 whitespace-nowrap" style={{ left: `${(chartX(index, dates.length, WIDTH, LEFT, RIGHT) / WIDTH) * 100}%` }}>{dateLabel(dates[index])}</span>)}</div>; }
function AxisCaption({ unit, balance = false }: { unit: string; balance?: boolean }) { return <p className="text-xs text-muted-foreground">Fecha · {balance ? "balance energético (kcal)" : unit}</p>; }
function YGrid({ domain, unit }: { domain: ReturnType<typeof chartDomain>; unit: ChartUnit }) { return <>{[0, 1 / 3, 2 / 3, 1].map((step) => { const value = domain.max - (domain.max - domain.min) * step; const y = chartY(value, domain, HEIGHT); return <g key={step}><line x1={LEFT} x2={WIDTH - RIGHT} y1={y} y2={y} className="stroke-border" strokeDasharray="2 3" /><text x={LEFT - 6} y={y + 3} textAnchor="end" className="fill-muted-foreground text-[9px]">{formatChartValue(value, unit)}</text></g>; })}</>; }
function dateHitBounds(index: number, count: number) { const center = chartX(index, count, WIDTH, LEFT, RIGHT); const previous = index === 0 ? LEFT : (chartX(index - 1, count, WIDTH, LEFT, RIGHT) + center) / 2; const next = index === count - 1 ? WIDTH - RIGHT : (center + chartX(index + 1, count, WIDTH, LEFT, RIGHT)) / 2; return { x: previous, width: next - previous }; }

function LineChart({ dates, series, unit, description }: { dates: string[]; series: LineSeries[]; unit: ChartUnit; description: string }) {
  const domain = chartDomain(series.flatMap((item) => item.values));
  const [selected, setSelected] = useState(() => Math.max(...series.flatMap((item) => item.values.map((value, index) => value === null ? -1 : index)), 0));
  const selectedDate = dates[selected] ?? dates[0];
  return <div className="space-y-2"><AxisCaption unit={unit} /><div className="h-40 min-w-0"><svg className="size-full overflow-visible" viewBox={`0 0 ${WIDTH} ${HEIGHT}`} preserveAspectRatio="none" role="img" aria-label={description}><YGrid domain={domain} unit={unit} />{series.map((item) => lineSegments(item.values, domain, WIDTH, HEIGHT, LEFT, RIGHT).map((segment, index) => <polyline key={`${item.label}-${index}`} points={points(segment)} className={item.className} fill="none" stroke="currentColor" strokeWidth={item.width ?? 2} strokeDasharray={item.dash} vectorEffect="non-scaling-stroke" strokeLinecap="round" strokeLinejoin="round" />))}{dates.map((value, index) => { const known = series.some((item) => item.values[index] !== null); if (!known) return null; const hit = dateHitBounds(index, dates.length); return <rect key={value} x={hit.x} y="0" width={hit.width} height={HEIGHT} fill="transparent" role="button" tabIndex={0} aria-label={`${dateLabel(value, true)}. Ver valores de ${unit}.`} onClick={() => setSelected(index)} onKeyDown={(event) => keySelect(event, () => setSelected(index))} />; })}{series.map((item) => item.values.map((value, index) => value === null ? null : <circle key={`${item.label}-${index}`} cx={chartX(index, dates.length, WIDTH, LEFT, RIGHT)} cy={chartY(value, domain, HEIGHT)} r={selected === index ? 4.5 : 2.5} className={item.className} fill="currentColor" stroke="var(--card)" strokeWidth="1.25" pointerEvents="none" />))}</svg></div><DateLabels dates={dates} /><ChartDetail title={dateLabel(selectedDate, true)} items={series.map((item) => ({ label: item.label, value: item.values[selected] === null ? "Sin dato" : formatChartValue(item.values[selected]!, unit) }))} /></div>;
}

function BalanceChart({ days }: { days: NutritionReportDay[] }) {
  const values = days.map((day) => day.isComplete ? day.energyBalanceKcal : null); const known = values.filter((value): value is number => value !== null); const [selected, setSelected] = useState(() => Math.max(...values.map((value, index) => value === null ? -1 : index), 0));
  if (!known.length) return <p className="py-8 text-sm text-muted-foreground">No hay días terminados con balance energético comparable.</p>;
  const domain = chartDomain(values, true); const zeroY = chartY(0, domain, HEIGHT); const barWidth = Math.max(3, Math.min(18, (WIDTH - LEFT - RIGHT) / Math.max(days.length, 1) - 2)); const value = values[selected] ?? null;
  const semantic = value === null ? "Sin dato" : value < 0 ? `Déficit estimado: ${formatChartValue(Math.abs(value), "kcal")}` : value > 0 ? `Superávit estimado: ${formatChartValue(value, "kcal")}` : "Balance estimado: 0 kcal";
  return <div className="space-y-2"><AxisCaption unit="kcal" balance /><div className="h-40 min-w-0"><svg className="size-full overflow-visible" viewBox={`0 0 ${WIDTH} ${HEIGHT}`} preserveAspectRatio="none" role="img" aria-label="Balance diario. Valores negativos son déficit estimado y positivos superávit estimado."><YGrid domain={domain} unit="kcal" /><line x1={LEFT} x2={WIDTH - RIGHT} y1={zeroY} y2={zeroY} className="stroke-foreground/55" strokeDasharray="3 3" />{values.map((item, index) => { if (item === null) return null; const x = chartX(index, days.length, WIDTH, LEFT, RIGHT) - barWidth / 2; const y = chartY(item, domain, HEIGHT); const hit = dateHitBounds(index, days.length); return <g key={days[index]!.date}><rect x={x} y={Math.min(y, zeroY)} width={barWidth} height={Math.max(1, Math.abs(y - zeroY))} rx="1" className={item < 0 ? "fill-primary" : "fill-foreground/55"} pointerEvents="none" /><rect x={hit.x} y="0" width={hit.width} height={HEIGHT} fill="transparent" role="button" tabIndex={0} aria-label={`${dateLabel(days[index]!.date, true)}. ${item < 0 ? "Déficit" : "Superávit"} estimado: ${formatChartValue(Math.abs(item), "kcal")}.`} onClick={() => setSelected(index)} onKeyDown={(event) => keySelect(event, () => setSelected(index))} /></g>; })}</svg></div><DateLabels dates={days.map((day) => day.date)} /><ChartDetail title={dateLabel(days[selected]?.date ?? days[0]!.date, true)} items={[{ label: "Balance", value: semantic }]} description="Base 0: abajo es déficit estimado y arriba es superávit estimado." /></div>;
}

function StepsChart({ days }: { days: NutritionReportDay[] }) {
  const values = days.map((day) => day.isComplete ? day.steps : null); const known = values.filter((value): value is number => value !== null); const [selected, setSelected] = useState(() => Math.max(...values.map((value, index) => value === null ? -1 : index), 0));
  if (!known.length) return <p className="py-8 text-sm text-muted-foreground">Registrá pasos algunos días para ver la tendencia.</p>;
  const domain = chartDomain(values, true); const baseline = chartY(0, domain, HEIGHT); const barWidth = Math.max(3, Math.min(18, (WIDTH - LEFT - RIGHT) / Math.max(days.length, 1) - 2));
  return <div className="space-y-2"><AxisCaption unit="pasos" /><div className="h-40 min-w-0"><svg className="size-full overflow-visible" viewBox={`0 0 ${WIDTH} ${HEIGHT}`} preserveAspectRatio="none" role="img" aria-label="Pasos registrados por fecha."><YGrid domain={domain} unit="pasos" />{values.map((value, index) => { if (value === null) return null; const hit = dateHitBounds(index, days.length); return <g key={days[index]!.date}><rect x={chartX(index, days.length, WIDTH, LEFT, RIGHT) - barWidth / 2} y={chartY(value, domain, HEIGHT)} width={barWidth} height={Math.max(1, baseline - chartY(value, domain, HEIGHT))} rx="1" className="fill-primary/75" pointerEvents="none" /><rect x={hit.x} y="0" width={hit.width} height={HEIGHT} fill="transparent" role="button" tabIndex={0} aria-label={`${dateLabel(days[index]!.date, true)}. ${formatChartValue(value, "pasos")}.`} onClick={() => setSelected(index)} onKeyDown={(event) => keySelect(event, () => setSelected(index))} /></g>; })}</svg></div><DateLabels dates={days.map((day) => day.date)} /><ChartDetail title={dateLabel(days[selected]?.date ?? days[0]!.date, true)} items={[{ label: "Pasos", value: values[selected] === null ? "Sin dato" : formatChartValue(values[selected]!, "pasos") }]} /></div>;
}

function ChartCard({ title, children, className = "" }: { title: string; children: React.ReactNode; className?: string }) { return <Card className={`surface-elevated ${className}`}><CardHeader className="pb-1"><CardTitle>{title}</CardTitle></CardHeader><CardContent>{children}</CardContent></Card>; }

export function NutritionReportCharts({ days }: { days: NutritionReportDay[] }) {
  const chronological = [...days].reverse(); const dates = chronological.map((day) => day.date);
  const energy: LineSeries[] = [{ label: "Consumido", values: chronological.map((day) => day.hasNutrition ? day.calories : null), className: "text-primary", width: 2.5 }, { label: "Objetivo", values: chronological.map((day) => day.hasNutrition ? day.targetCalories : null), className: "text-muted-foreground", dash: "5 4" }, { label: "Gasto estimado", values: chronological.map((day) => day.hasNutrition ? day.expenditureKcal : null), className: "text-foreground/70", dash: "1 3", width: 2.5 }];
  const protein: LineSeries[] = [{ label: "Consumida", values: chronological.map((day) => day.hasNutrition ? day.proteinG : null), className: "text-primary", width: 2.5 }, { label: "Objetivo", values: chronological.map((day) => day.hasNutrition ? day.targetProteinG : null), className: "text-muted-foreground", dash: "5 4" }];
  const water: LineSeries[] = [{ label: "Agua", values: chronological.map((day) => day.isComplete ? day.waterL : null), className: "text-primary", width: 2.5 }, { label: "Objetivo", values: chronological.map((day) => day.isComplete ? day.targetWaterL : null), className: "text-muted-foreground", dash: "5 4" }];
  const waterKnown = water.some((series) => series.values.some((value) => value !== null));
  return <section className="space-y-4" aria-labelledby="nutrition-trends-title"><div><div className="flex flex-wrap items-center gap-2"><h2 id="nutrition-trends-title" className="text-lg font-semibold tracking-tight">Tendencias</h2>{chronological.some((day) => day.isToday) ? <span className="rounded-full bg-primary/10 px-2 py-0.5 text-[10px] font-semibold text-primary">Hoy · En curso</span> : null}</div><p className="text-xs text-muted-foreground">Los huecos representan días sin dato; hoy no altera los resúmenes finales.</p></div><ChartCard title="Tendencia de energía"><div className="space-y-3"><ChartLegend series={energy} /><LineChart dates={dates} series={energy} unit="kcal" description="Tendencia de energía. Eje horizontal: fecha. Eje vertical: calorías." /></div></ChartCard><ChartCard title="Balance diario"><BalanceChart days={chronological} /></ChartCard><ChartCard title="Proteína"><div className="space-y-3"><ChartLegend series={protein} /><LineChart dates={dates} series={protein} unit="g" description="Tendencia de proteína. Eje horizontal: fecha. Eje vertical: gramos." /></div></ChartCard><div className="grid gap-4 lg:grid-cols-2"><ChartCard title="Agua">{waterKnown ? <div className="space-y-3"><ChartLegend series={water} /><LineChart dates={dates} series={water} unit="L" description="Tendencia de agua. Eje horizontal: fecha. Eje vertical: litros." /><p className="text-xs text-muted-foreground">El mate se mantiene separado del agua.</p></div> : <p className="py-8 text-sm text-muted-foreground">Registrá agua algunos días para ver la tendencia.</p>}</ChartCard><ChartCard title="Pasos"><StepsChart days={chronological} /></ChartCard></div></section>;
}
