import {act,fireEvent,render} from '@testing-library/react-native';
import {describe,expect,it,jest} from '@jest/globals';
import {OwnlevelThemeProvider} from '@/design-system';
import {ConfigurationController,type ConfigApi} from './config-controller';
import {ConfigurationIntentRepository} from './config-storage';
import {ConfigurationEditor} from './config-editor';
import {configFixture} from './config-fixture.test-helper';
jest.mock('expo-symbols',()=>({SymbolView:()=>null}));
const meta={durationMs:0,httpStatus:200,outcome:'ok' as const};
function fixture(){const map=new Map<string,string>(),port={getItem:async(k:string)=>map.get(k)??null,setItem:async(k:string,v:string)=>{map.set(k,v);},removeItem:async(k:string)=>{map.delete(k);}};
 const api:ConfigApi={read:jest.fn<ConfigApi['read']>().mockResolvedValue({status:'ok',data:configFixture,meta}),write:jest.fn<ConfigApi['write']>().mockImplementation(async i=>({status:'ok',data:{status:'confirmed',operation:i.operation,date:i.date,version:'b'.repeat(64),weightRecorded:i.operation==='physical'},meta})),refreshToday:async()=>true};
 const c=new ConfigurationController(api,new ConfigurationIntentRepository(port,'owner'),()=>{});const element=()=><OwnlevelThemeProvider initialMode="light"><ConfigurationEditor controller={c} state={c.getSnapshot()}/></OwnlevelThemeProvider>;
 const view=render(element());c.subscribe(()=>view.rerender(element()));return {c,api,view,open:async()=>act(async()=>{await c.initialize();c.open();})};}
describe('Native Configuration',()=>{
 it('plan seven weekdays, explicit zero and canonical save',async()=>{const f=fixture();await f.open();fireEvent.press(f.view.getByText('Editar plan nutricional'));expect(f.view.getByLabelText('Lunes · Proteína (g)').props.value).toBe('0');fireEvent.changeText(f.view.getByLabelText('Agua base (L)'),'2,5');fireEvent.changeText(f.view.getByLabelText('Martes · Calorías (kcal)'),'2100');await act(async()=>{fireEvent.press(f.view.getByText('Guardar plan nutricional'));});expect(f.api.write).toHaveBeenCalledWith(expect.objectContaining({operation:'plan',fields:expect.objectContaining({baseWaterL:2.5,weekdays:expect.arrayContaining([{weekday:2,calorieTargetKcal:2100,proteinTargetG:0}])})}));});
 it('energy automatic/custom and physical editor preserve drafts on refresh',async()=>{const f=fixture();await f.open();fireEvent.press(f.view.getByText('Editar energía'));fireEvent.press(f.view.getByText('Personalizado'));fireEvent.changeText(f.view.getByLabelText('Gasto base personalizado (kcal)'),'2600');await act(async()=>{await f.c.load();});expect(f.view.getByLabelText('Gasto base personalizado (kcal)').props.value).toBe('2600');await act(async()=>{fireEvent.press(f.view.getByText('Guardar energía'));});expect(f.api.write).toHaveBeenCalledWith(expect.objectContaining({operation:'energy',fields:expect.objectContaining({baseExpenditureMode:'custom',customBaseExpenditureKcal:2600})}));
  fireEvent.press(f.view.getByText('Editar datos físicos'));fireEvent.changeText(f.view.getByLabelText('Peso (kg)'),'81,25');await act(async()=>{fireEvent.press(f.view.getByText('Guardar datos físicos'));});expect(f.api.write).toHaveBeenLastCalledWith(expect.objectContaining({operation:'physical',fields:expect.objectContaining({weightKg:81.25})}));});
 it('pending blocks inputs and conflict shows truth without replacing draft',async()=>{const f=fixture();await f.open();fireEvent.press(f.view.getByText('Editar datos físicos'));fireEvent.changeText(f.view.getByLabelText('Peso (kg)'),'82');let resolve!:(r:Awaited<ReturnType<ConfigApi['write']>>)=>void;
  jest.mocked(f.api.write).mockImplementation(()=>new Promise(r=>{resolve=r;}));await act(async()=>{fireEvent.press(f.view.getByText('Guardar datos físicos'));});expect(f.view.getByLabelText('Peso (kg)').props.editable).toBe(false);
  await act(async()=>{resolve({status:'conflict',code:'PHYSICAL_CHANGED',message:'Datos cambiados',meta:{...meta,outcome:'conflict'}});});expect(f.view.getByLabelText('Peso (kg)').props.value).toBe('82');expect(f.view.getByText('Valores actuales del servidor')).toBeTruthy();fireEvent.press(f.view.getByText('Revisar mi borrador con esta versión'));expect(f.view.getByLabelText('Peso (kg)').props.editable).toBe(true);
 });
 it('legacy adoption is explicit and unavailable is independent',async()=>{const f=fixture();jest.mocked(f.api.read).mockResolvedValue({status:'ok',data:{...configFixture,plan:configFixture.plan.status==='ok'?{status:'ok',data:{...configFixture.plan.data,source:'legacy'}}:configFixture.plan,energy:{status:'unavailable'}},meta});await f.open();expect(f.view.getByText(/Configuración heredada/)).toBeTruthy();expect(f.view.queryByText('Editar energía')).toBeNull();expect(f.view.getByText('Editar datos físicos')).toBeTruthy();});
});
