import {describe,expect,it,jest} from '@jest/globals';
import {SavedController,type SavedApi} from './saved-controller';
import {SavedIntentRepository} from './saved-storage';
import {savedDraft,validateSavedDraft,draftTotals} from './saved-model';
import {personalSaved,savedReceipt,savedId} from './saved-fixture.test-helper';
import {personalFood} from './food-fixture.test-helper';
const meta={durationMs:1,httpStatus:200,outcome:'ok' as const},failure={status:'unavailable' as const,reason:'server' as const,meta:{...meta,httpStatus:503,outcome:'unavailable' as const}},settle=async()=>{for(let n=0;n<10;n++)await Promise.resolve();};
function fixture(){const map=new Map<string,string>(),port={getItem:async(k:string)=>map.get(k)??null,setItem:async(k:string,v:string)=>{map.set(k,v);},removeItem:async(k:string)=>{map.delete(k);}},repo=new SavedIntentRepository(port,'owner'),invalidate=jest.fn();
 const api:SavedApi={foods:jest.fn<SavedApi['foods']>().mockResolvedValue({status:'ok',data:{status:'ok',foods:[personalFood]},meta}),list:jest.fn<SavedApi['list']>().mockResolvedValue({status:'ok',data:{status:'ok',meals:[personalSaved]},meta}),detail:jest.fn<SavedApi['detail']>().mockResolvedValue({status:'ok',data:{status:'ok',meal:personalSaved},meta}),write:jest.fn<SavedApi['write']>().mockImplementation(async i=>({status:'ok',data:{...savedReceipt,operation:i.operation,...(i.operation==='delete'?{version:null,updatedAt:null}:{})},meta}))};
 const c=new SavedController(api,repo,invalidate,()=>`key:${map.size}`);return {c,api,repo,map,invalidate,open:async()=>{await c.initialize();c.open();await settle();}};
}
describe('Reliable Saved Meals drafts and mutations',()=>{
 it('ordered ingredients can move without modifying their snapshots',async()=>{const f=fixture();await f.open();f.c.begin(undefined,'composite');f.c.addIngredient(personalFood);const second={...personalFood,id:'42300000-0000-4000-8000-000000000099',name:'SEGUNDO'};f.c.addIngredient(second);f.c.moveIngredient(1,-1);expect(f.c.getSnapshot().draft!.items.map(i=>i.food?.id)).toEqual([second.id,personalFood.id]);expect(f.c.getSnapshot().draft!.items[1].food).toEqual(personalFood);});
 it('manual null/zero, decimal macros, integer calories and name validation',()=>{const d=savedDraft(personalSaved);expect(d.calories).toBe('');expect(d.proteinG).toBe('0');expect(validateSavedDraft(d).fields).toMatchObject({calories:null,proteinG:0,fatG:1.25});for(const patch of [{calories:'22,5'},{proteinG:'-1'},{name:''},{proteinG:'',fatG:''}])expect(validateSavedDraft({...d,...patch}).fields).toBeUndefined();});
 it('composed selection captures Food, forbids duplicate, preserves 3-decimal base without silently rounding quantity',async()=>{const f=fixture();await f.open();f.c.begin(undefined,'composite');f.c.change('name','Compuesta');f.c.addIngredient(personalFood);f.c.addIngredient(personalFood);expect(f.c.getSnapshot().draft!.items).toHaveLength(1);expect(f.c.getSnapshot().draft!.items[0].quantity).toBe('');expect(validateSavedDraft(f.c.getSnapshot().draft!).fields).toBeUndefined();f.c.quantity(0,'0,25');expect(draftTotals(f.c.getSnapshot().draft!)?.calories).toBe(45);expect(validateSavedDraft(f.c.getSnapshot().draft!).fields?.items[0]).toMatchObject({kind:'food',version:personalFood.version,quantity:0.25});f.c.removeIngredient(0);expect(f.c.getSnapshot().draft!.items).toEqual([]);});
 it('persist before send, gate double taps, reread truth and refresh Quick',async()=>{const f=fixture();await f.open();f.c.begin(personalSaved);f.c.change('calories','200');(f.api.write as jest.Mock<SavedApi['write']>).mockImplementation(async i=>{expect((await f.repo.read())!.intent).toEqual(i);return {status:'ok',data:{...savedReceipt,operation:'update'},meta};});await Promise.all([f.c.save(),f.c.save()]);expect(f.api.write).toHaveBeenCalledTimes(1);expect(f.api.detail).toHaveBeenCalledWith(savedId);expect(await f.repo.read()).toBeNull();expect(f.invalidate).toHaveBeenCalledTimes(1);});
 it.each(['update','archive','reactivate','delete'] as const)('%s uses CAS captured version',async operation=>{const f=fixture();await f.open();f.c.begin(personalSaved);await f.c.save(operation);expect(f.api.write).toHaveBeenCalledWith(expect.objectContaining({operation,id:savedId,expectedVersion:personalSaved.version}));});
 it('foreground/refresh preserve draft; stale catalog response cannot replace newer filter',async()=>{const f=fixture();await f.open();f.c.begin(personalSaved);f.c.change('calories','500');await f.c.load();expect(f.c.getSnapshot().draft!.calories).toBe('500');let resolve!:(v:Awaited<ReturnType<SavedApi['list']>>)=>void;(f.api.list as jest.Mock<SavedApi['list']>).mockImplementationOnce(()=>new Promise(r=>{resolve=r;}));f.c.query('old');f.c.query('new','archived');await settle();resolve({status:'ok',data:{status:'ok',meals:[]},meta});await settle();expect(f.c.getSnapshot().meals).toEqual([personalSaved]);expect(f.c.getSnapshot().filter).toBe('archived');});
 it('CAS conflict preserves draft and requires explicit review',async()=>{const f=fixture();await f.open();f.c.begin(personalSaved);f.c.change('calories','300');const truth={...personalSaved,version:'b'.repeat(64),calories:400};(f.api.detail as jest.Mock<SavedApi['detail']>).mockResolvedValue({status:'ok',data:{status:'ok',meal:truth},meta});(f.api.write as jest.Mock<SavedApi['write']>).mockResolvedValueOnce({status:'conflict',code:'SAVED_CHANGED',message:'changed',meta:{...meta,outcome:'conflict'}});await f.c.save();await f.c.save();expect(f.api.write).toHaveBeenCalledTimes(1);expect(f.c.getSnapshot().draft!.calories).toBe('300');f.c.reviewTruth();expect(f.c.getSnapshot().editing!.version).toBe(truth.version);await f.c.save();expect(f.api.write).toHaveBeenLastCalledWith(expect.objectContaining({expectedVersion:truth.version}));});
 it('ambiguous write survives remount and recovers the same intent explicitly',async()=>{const f=fixture();await f.open();f.c.begin(personalSaved);(f.api.write as jest.Mock<SavedApi['write']>).mockResolvedValueOnce(failure);await f.c.save();const intent=(await f.repo.read())!.intent;const restored=new SavedController(f.api,f.repo,f.invalidate);await restored.initialize();expect(f.api.write).toHaveBeenCalledTimes(1);expect(restored.getSnapshot().phase).toBe('uncertain');await restored.recover();expect(f.api.write).toHaveBeenLastCalledWith(intent);expect(await f.repo.read()).toBeNull();});
 it('confirmed receipt survives read failure without resending the mutation',async()=>{const f=fixture();await f.open();f.c.begin(personalSaved);(f.api.detail as jest.Mock<SavedApi['detail']>).mockResolvedValueOnce(failure);await f.c.save();expect((await f.repo.read())?.receipt).toBeDefined();await f.c.recover();expect(f.api.write).toHaveBeenCalledTimes(1);expect(await f.repo.read()).toBeNull();});
 it('unavailable differs from an empty catalog, corrupt intent blocks',async()=>{const f=fixture();await f.open();(f.api.list as jest.Mock<SavedApi['list']>).mockResolvedValueOnce(failure);await f.c.load();expect(f.c.getSnapshot().listError).toBe(true);expect(f.c.getSnapshot().meals).toHaveLength(1);f.map.set(f.repo.key,'{}');const c=new SavedController(f.api,f.repo);await c.initialize();expect(c.getSnapshot().phase).toBe('blocked');});
 it('existing components keep base snapshots across Food refresh and quantity edits',async()=>{
  const f=fixture();await f.open();const item={id:savedId,label:'CAPTURED',quantity:0.25,unit:personalFood.servingUnit,baseQuantity:0.125,baseCalories:22.5,baseProteinG:null,baseCarbsG:1.11,baseFatG:0,sourceFoodId:personalFood.id,position:0};
  const composed={...personalSaved,templateType:'composite' as const,items:[item],calories:45,proteinG:null,carbsG:2.22,fatG:0};
  f.c.begin(composed);f.c.quantity(0,'0,5');(f.api.foods as jest.Mock<SavedApi['foods']>).mockResolvedValue({status:'ok',data:{status:'ok',foods:[{...personalFood,calories:99}]},meta});await f.c.loadFoods();
  expect(f.c.getSnapshot().draft!.items[0].snapshot!.baseCalories).toBe(22.5);expect(draftTotals(f.c.getSnapshot().draft!)!.calories).toBe(90);
  await f.c.save();expect(f.api.write).toHaveBeenCalledWith(expect.objectContaining({fields:expect.objectContaining({items:[{kind:'snapshot',id:savedId,quantity:0.5}]})}));
 });
 it('Web replacing item IDs can be reviewed while preserving local quantity draft',async()=>{
  const f=fixture();await f.open();const item={id:savedId,label:'CAPTURED',quantity:1,unit:'g',baseQuantity:1,baseCalories:20,baseProteinG:0,baseCarbsG:0,baseFatG:0,sourceFoodId:personalFood.id,position:0};
  const composed={...personalSaved,templateType:'composite' as const,items:[item],calories:20};f.c.begin(composed);f.c.quantity(0,'2');
  const newId='42300000-0000-4000-8000-000000000099',truth={...composed,version:'b'.repeat(64),items:[{...item,id:newId}]};
  (f.api.detail as jest.Mock<SavedApi['detail']>).mockResolvedValue({status:'ok',data:{status:'ok',meal:truth},meta});(f.api.write as jest.Mock<SavedApi['write']>).mockResolvedValueOnce({status:'conflict',code:'SAVED_CHANGED',message:'changed',meta:{...meta,outcome:'conflict'}});
  await f.c.save();expect(f.c.getSnapshot().draft!.items[0].snapshot!.id).toBe(savedId);f.c.reviewTruth();expect(f.c.getSnapshot().draft!.items[0].quantity).toBe('2');expect(f.c.getSnapshot().draft!.items[0].snapshot!.id).toBe(newId);
 });

});
