"use client";

import { Dialog } from "@base-ui/react/dialog";
import { AlertTriangle, Pencil, Plus, Ruler, Trash2, X } from "lucide-react";
import { useMemo, useState, useTransition, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { ChartDetail } from "@/components/ui/chart-detail";
import { DateField } from "@/components/ui/date-field";
import { chartDomain, chartTickIndexes, chartX, chartY, chartYAxisTicks, formatChartValue, lineSegments } from "@/lib/chart-core";
import { BODY_MEASUREMENT_FIELDS, type BodyMeasurement, type BodyMeasurementField } from "@/lib/body-measurement-types";
import { deleteBodyMeasurementAction, saveBodyMeasurementAction } from "@/app/(app)/train/body/actions";

const labels: Record<BodyMeasurementField, string> = {
  waist_cm: "Cintura", abdomen_cm: "Abdomen", chest_cm: "Pecho", hip_cm: "Cadera",
  arm_cm: "Brazo (legacy)", arm_right_cm: "Brazo derecho", arm_left_cm: "Brazo izquierdo",
  thigh_cm: "Muslo (legacy)", thigh_right_cm: "Muslo derecho", thigh_left_cm: "Muslo izquierdo",
  calf_right_cm: "Pantorrilla derecha", calf_left_cm: "Pantorrilla izquierda",
};
const inputNames: Record<BodyMeasurementField, string> = {
  waist_cm: "waistCm", abdomen_cm: "abdomenCm", chest_cm: "chestCm", hip_cm: "hipCm",
  arm_cm: "armCm", arm_right_cm: "armRightCm", arm_left_cm: "armLeftCm",
  thigh_cm: "thighCm", thigh_right_cm: "thighRightCm", thigh_left_cm: "thighLeftCm",
  calf_right_cm: "calfRightCm", calf_left_cm: "calfLeftCm",
};
type Values = Record<BodyMeasurementField, string>;
const emptyValues = () => Object.fromEntries(BODY_MEASUREMENT_FIELDS.map((field) => [field, ""])) as Values;
const formatCm = (value: number | null) => value == null ? "—" : `${new Intl.NumberFormat("es-AR", { maximumFractionDigits: 2 }).format(value)} cm`;
function formatDate(value: string) { return new Intl.DateTimeFormat("es-AR", { day: "numeric", month: "short", year: "numeric", timeZone: "America/Argentina/Cordoba" }).format(new Date(`${value}T12:00:00Z`)).replace(" de ", " ").replace(".", ""); }
function toValues(entry: BodyMeasurement | null): Values { return entry ? Object.fromEntries(BODY_MEASUREMENT_FIELDS.map((field) => [field, entry[field] == null ? "" : String(entry[field])])) as Values : emptyValues(); }

function Sheet({ children, open, onOpenChange }: { children: ReactNode; open: boolean; onOpenChange: (open: boolean) => void }) {
  return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Backdrop className="fixed inset-0 z-[82] bg-black/45 backdrop-blur-[2px]" /><Dialog.Viewport className="fixed inset-0 z-[83] flex items-end justify-center overflow-hidden sm:items-center sm:p-6"><Dialog.Popup className="max-h-[calc(100dvh-env(safe-area-inset-bottom))] w-full overflow-y-auto rounded-t-[1.5rem] bg-card p-5 text-card-foreground shadow-2xl outline-none sm:max-w-2xl sm:rounded-2xl sm:border">{children}</Dialog.Popup></Dialog.Viewport></Dialog.Portal></Dialog.Root>;
}

function MeasurementChart({ entries, field }: { entries: BodyMeasurement[]; field: BodyMeasurementField }) {
  const [selected, setSelected] = useState(-1);
  const points = entries.filter((entry) => entry[field] !== null);
  if (!points.length) return <p className="py-8 text-center text-sm text-muted-foreground">Todavía no hay registros de {labels[field].toLowerCase()}.</p>;
  const width = 360; const height = 164; const left = 50; const right = 12; const top = 12; const bottom = 30;
  const values = points.map((entry) => entry[field] as number); const domain = chartDomain(values); const coordinates = lineSegments(values, domain, width, height, left, right, top, bottom)[0] ?? [];
  const selectedIndex = selected < 0 ? points.length - 1 : Math.min(selected, points.length - 1);
  return <div className="space-y-2"><p className="text-xs text-muted-foreground">Fecha · {labels[field]} (cm)</p><svg className="h-auto w-full text-primary" viewBox={`0 0 ${width} ${height}`} role="group" aria-label={`Evolución de ${labels[field]}. Eje horizontal: fecha. Eje vertical: centímetros.`}>{chartYAxisTicks(domain, 4).map((value) => { const y = chartY(value, domain, height, top, bottom); return <g key={value}><line x1={left} x2={width - right} y1={y} y2={y} stroke="currentColor" strokeOpacity=".14" /><text x={left - 7} y={y + 3.5} textAnchor="end" className="fill-muted-foreground text-[10px]">{formatChartValue(value, "cm")}</text></g>; })}{coordinates.length > 1 ? <polyline points={coordinates.map(({ x, y }) => `${x},${y}`).join(" ")} fill="none" stroke="currentColor" strokeWidth="2.25" /> : null}{coordinates.map(({ index, x, y }) => { const point = points[index]!; const value = values[index]!; return <g key={point.id}><circle cx={x} cy={y} r="11" fill="transparent" role="button" tabIndex={0} aria-label={`${formatDate(point.measured_on)}. ${labels[field]}: ${formatChartValue(value, "cm")}.`} onClick={() => setSelected(index)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setSelected(index); } }} /><circle cx={x} cy={y} r={selectedIndex === index ? 5 : 3.75} className="fill-card stroke-primary" strokeWidth="2" pointerEvents="none" /></g>; })}</svg><div className="relative h-4 text-[10px] text-muted-foreground" aria-hidden>{chartTickIndexes(points.length, 3).map((index) => <span key={points[index]!.id} className="absolute -translate-x-1/2 whitespace-nowrap" style={{ left: `${(chartX(index, points.length, width, left, right) / width) * 100}%` }}>{formatDate(points[index]!.measured_on).replace(/\s\d{4}$/, "")}</span>)}</div><ChartDetail title={formatDate(points[selectedIndex]!.measured_on)} items={[{ label: labels[field], value: formatChartValue(values[selectedIndex]!, "cm") }]} /></div>;
}

export function BodyMeasurements({ initialEntries, today }: { initialEntries: BodyMeasurement[]; today: string }) {
  const [entries,setEntries]=useState(initialEntries), [selectedField,setSelectedField]=useState<BodyMeasurementField>("waist_cm");
  const [editing,setEditing]=useState<BodyMeasurement|null>(null), [formOpen,setFormOpen]=useState(false), [date,setDate]=useState(today), [values,setValues]=useState<Values>(emptyValues);
  const [condition,setCondition]=useState(""), [notes,setNotes]=useState(""), [deleteTarget,setDeleteTarget]=useState<BodyMeasurement|null>(null), [error,setError]=useState<string|null>(null);
  const [pending,startTransition]=useTransition(), latest=entries.at(-1)??null, ordered=useMemo(()=>[...entries].reverse(),[entries]);
  const openCreate=()=>{setError(null);setEditing(null);setDate(today);setValues(emptyValues());setCondition("");setNotes("");setFormOpen(true);};
  const openEdit=(entry:BodyMeasurement)=>{setError(null);setEditing(entry);setDate(entry.measured_on);setValues(toValues(entry));setCondition(entry.condition??"");setNotes(entry.notes??"");setFormOpen(true);};
  const save=()=>startTransition(async()=>{const payload: Record<string,string|undefined>={id:editing?.id,measuredOn:date,condition,notes}; for(const field of BODY_MEASUREMENT_FIELDS) payload[inputNames[field]]=values[field]; const result=await saveBodyMeasurementAction(payload as Parameters<typeof saveBodyMeasurementAction>[0]); if(!result.ok||!result.entry){setError(result.ok?"No se pudieron guardar las medidas.":result.error);return;} setEntries((current)=>[...current.filter((entry)=>entry.id!==result.entry!.id&&entry.measured_on!==result.entry!.measured_on),result.entry!].sort((a,b)=>a.measured_on.localeCompare(b.measured_on)));setFormOpen(false);});
  const remove=()=>{if(!deleteTarget)return;startTransition(async()=>{const result=await deleteBodyMeasurementAction({id:deleteTarget.id});if(!result.ok){setError(result.error);return;}setEntries((current)=>current.filter((entry)=>entry.id!==deleteTarget.id));setDeleteTarget(null);});};

  return <section className="space-y-3" aria-labelledby="body-measurements-title">
    <div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><Ruler className="size-4 text-primary"/><div><h2 id="body-measurements-title" className="text-base font-semibold lg:text-lg">Medidas corporales</h2><p className="text-sm text-muted-foreground">Mediciones independientes por fecha.</p></div></div><Button type="button" size="sm" onClick={openCreate}><Plus className="size-4"/>Registrar</Button></div>
    <Card className="surface-elevated"><CardContent className="pt-4"><p className="text-xs text-muted-foreground">Últimas medidas{latest?` · ${formatDate(latest.measured_on)}`:""}</p><div className="mt-3 grid grid-cols-2 gap-x-4 gap-y-2 border-t pt-3 sm:grid-cols-4">{BODY_MEASUREMENT_FIELDS.filter((field)=>latest?.[field]!=null).map((field)=><div key={field}><span className="text-xs text-muted-foreground">{labels[field]}</span><p className="metric-number text-sm font-semibold">{formatCm(latest?.[field]??null)}</p></div>)}{latest?.condition?<div><span className="text-xs text-muted-foreground">Condición</span><p className="text-sm font-semibold">{latest.condition}</p></div>:null}</div></CardContent></Card>
    <section className="space-y-2"><div className="flex items-center justify-between gap-2"><h3 className="text-sm font-semibold">Evolución</h3><select value={selectedField} onChange={(e)=>setSelectedField(e.target.value as BodyMeasurementField)} className="h-10 max-w-[65%] rounded-lg border bg-background px-3 text-sm">{BODY_MEASUREMENT_FIELDS.map((field)=><option key={field} value={field}>{labels[field]}</option>)}</select></div><Card><CardContent className="pt-4"><MeasurementChart entries={entries} field={selectedField}/></CardContent></Card></section>
    <details className="rounded-xl border bg-card px-4 py-2"><summary className="min-h-10 cursor-pointer py-2 font-medium">Historial de medidas · {entries.length}</summary><div className="divide-y border-t">{ordered.map((entry)=><div key={entry.id} className="space-y-2 py-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium">{formatDate(entry.measured_on)}</p>{entry.quality_status==="suspect"?<p className="mt-1 inline-flex items-center gap-1 text-xs font-medium text-amber-600"><AlertTriangle className="size-3.5"/>Revisar medición</p>:null}</div><div className="flex"><Button size="sm" variant="ghost" onClick={()=>openEdit(entry)}><Pencil className="size-3.5"/>Editar</Button>{entry.import_run_id?null:<Button size="icon-sm" variant="ghost" className="text-muted-foreground hover:text-destructive" onClick={()=>setDeleteTarget(entry)}><Trash2 className="size-3.5"/><span className="sr-only">Eliminar</span></Button>}</div></div><div className="grid grid-cols-2 gap-x-4 text-xs text-muted-foreground sm:grid-cols-4">{BODY_MEASUREMENT_FIELDS.filter((field)=>entry[field]!=null).map((field)=><span key={field}>{labels[field]} <b className="font-medium text-foreground">{formatCm(entry[field])}</b></span>)}</div>{entry.condition?<p className="text-xs text-muted-foreground">Condición: {entry.condition}</p>:null}{entry.notes?<p className="text-xs text-muted-foreground">Notas: {entry.notes}</p>:null}{entry.quality_note?<p className="rounded-lg bg-amber-500/10 px-3 py-2 text-xs text-amber-700 dark:text-amber-300">{entry.quality_note}</p>:null}{entry.import_run_id?<p className="text-[11px] text-muted-foreground">Dato histórico importado. Su procedencia se conserva al editar.</p>:null}</div>)}{!ordered.length?<p className="py-4 text-sm text-muted-foreground">Todavía no registraste medidas.</p>:null}</div></details>
    {error?<p className="text-sm text-destructive" role="alert">{error}</p>:null}
    <Sheet open={formOpen} onOpenChange={(value)=>!pending&&setFormOpen(value)}><div className="flex items-center justify-between"><Dialog.Title className="font-semibold">{editing?"Editar medidas":"Registrar medidas"}</Dialog.Title><Dialog.Close className="flex size-10 items-center justify-center"><X className="size-4"/></Dialog.Close></div><div className="mt-4 space-y-4"><label className="min-w-0 space-y-1"><span className="text-sm font-medium">Fecha</span><DateField value={date} onChange={(e)=>setDate(e.target.value)}/></label><div className="grid grid-cols-2 gap-3">{BODY_MEASUREMENT_FIELDS.map((field)=><label key={field} className="space-y-1"><span className="text-sm font-medium">{labels[field]}</span><div className="flex items-center gap-1"><input value={values[field]} onChange={(e)=>setValues((current)=>({...current,[field]:e.target.value}))} inputMode="decimal" placeholder="—" className="h-11 min-w-0 flex-1 rounded-lg border bg-background px-3"/><span className="text-xs text-muted-foreground">cm</span></div></label>)}</div><label className="block space-y-1"><span className="text-sm font-medium">Condición</span><input value={condition} onChange={(e)=>setCondition(e.target.value)} className="h-11 w-full rounded-lg border bg-background px-3" placeholder="Opcional"/></label><label className="block space-y-1"><span className="text-sm font-medium">Notas</span><textarea value={notes} onChange={(e)=>setNotes(e.target.value)} className="min-h-20 w-full rounded-lg border bg-background px-3 py-2 text-sm" placeholder="Opcional"/></label><p className="text-xs text-muted-foreground">Completá al menos una medida. Los lados no se promedian.</p><Button type="button" className="h-11 w-full" disabled={pending} onClick={save}>{pending?"Guardando…":"Guardar"}</Button></div></Sheet>
    <Sheet open={Boolean(deleteTarget)} onOpenChange={(value)=>!value&&!pending&&setDeleteTarget(null)}><Dialog.Title className="font-semibold">¿Eliminar estas medidas?</Dialog.Title><Dialog.Description className="mt-2 text-sm text-muted-foreground">Esta acción sólo está disponible para registros manuales.</Dialog.Description><div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={()=>setDeleteTarget(null)}>Cancelar</Button><Button variant="destructive" disabled={pending} onClick={remove}>Eliminar</Button></div></Sheet>
  </section>;
}
